name: Maven Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: j17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw -B -U clean verify